apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-dev

resources:
  - ../../base
  - ingress.yaml

    # ATENTION name = image.name NOT name = spec.containers[0].name
images:
  - name: gabtec/demo-go-api
    newTag: v0.8.1
