apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idp-dev

resources:
  - service.yaml
  - deploy.yaml

images:
  # ATENTION name = image.name NOT name = spec.containers[0].name
  - name: gabtec/demo-go-api
    newTag: v0.1.0
