apiVersion: v1
kind: Service
metadata:
  name: demo-go-api
spec:
  selector:
    app: demo-go-api
  # type: LoadBalancer | ClusterIP | NodePort
  ports:
    - name: http
      port: 3000 # service port
      protocol: TCP
      targetPort: 3000 # container port
